### PR TITLE
Update msh_checkbox.dart fix initial value True.

### PR DESCRIPTION
**Pull request by dr4mohamed**
fix initial value True.

### CODE REVIEW

**Comment by HornMichaelS** [comment]
Thanks for the contribution! Would you mind explaining a bit the rationale for this change?

This would run the animation when the widget is initially built, even if the initial value is already true. That is most likely not the desired behavior for everyone, but you could consider adding it as a conditionally enabled behavior. Perhaps something like this:

```dart
MSHCheckBox(
  // ...
  runAnimationOnFirstBuild: true, // default to false
),
```

Please also format your code using the `dart_style` formatter for consistency.

Thank you!

**Comment by dr4mohamed** [comment]
in my case, i have checkbox in edit page , i can't run the animation based on the value because isn't always true or false,
the solution : run the animation based on the value , my code : 
`                              MSHCheckbox(
                                checkedColor: Colors.green,
                                style: MSHCheckboxStyle.fillScaleCheck,
                                size: 28,
                                value: _con.operation.warranty,
                                onChanged: (bool selected) {
                                  setState(() {
                                    _con.operation.warranty = selected;
                                  });
                                },
                              ),`

**Comment by HornMichaelS** [comment]
Sorry, I'm still not understanding the issue you're having - If you still want to have this pull request merged, would you mind sharing a reproducible example of your problem, the desired behavior, and the actual behavior you are seeing?

**Comment by HornMichaelS** [comment]
Hi @dr4mohamed,

Another user recently submitted a pull request, which I think addresses the issue which you were trying to fix here. I apologize that I did not understand the bug you were trying to fix, but you should find that [version 1.1.2](https://pub.dev/packages/msh_checkbox/versions/1.1.2) is working!

**Pull request closed without merging**
